"""Create processing runs table

Revision ID: 48ce23e455c8
Revises: 
Create Date: 2026-09-22 20:14:28.501859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48ce23e455c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('input_format', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('requires_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='ck_processing_runs_duration_ms_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_runs_document_type'), 'processing_runs', ['document_type'], unique=False)
    op.create_index('ix_processing_runs_document_type_created_at', 'processing_runs', ['document_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_processing_runs_processing_status'), 'processing_runs', ['processing_status'], unique=False)
    op.create_index(op.f('ix_processing_runs_profile'), 'processing_runs', ['profile'], unique=False)
    op.create_index(op.f('ix_processing_runs_requires_review'), 'processing_runs', ['requires_review'], unique=False)
    op.create_index('ix_processing_runs_status_created_at', 'processing_runs', ['processing_status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processing_runs_status_created_at', table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_requires_review'), table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_profile'), table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_processing_status'), table_name='processing_runs')
    op.drop_index('ix_processing_runs_document_type_created_at', table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_document_type'), table_name='processing_runs')
    op.drop_table('processing_runs')
    # ### end Alembic commands ###
