"""add processing run configuration identity

Revision ID: 6fc8c5caeaba
Revises: d58dc395f17f
Create Date: 2026-09-27 19:39:22.279505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fc8c5caeaba'
down_revision: Union[str, Sequence[str], None] = 'd58dc395f17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_runs', sa.Column('configuration_hash', sa.String(length=64), nullable=True))
    op.add_column('processing_runs', sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('processing_runs', sa.Column('configuration_schema_version', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_processing_runs_configuration_hash'), 'processing_runs', ['configuration_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_runs_configuration_hash'), table_name='processing_runs')
    op.drop_column('processing_runs', 'configuration_schema_version')
    op.drop_column('processing_runs', 'configuration_snapshot')
    op.drop_column('processing_runs', 'configuration_hash')
    # ### end Alembic commands ###
