"""Add processing run step timings

Revision ID: b88bfcb21ad6
Revises: 48ce23e455c8
Create Date: 2026-09-22 21:04:38.997661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b88bfcb21ad6'
down_revision: Union[str, Sequence[str], None] = '48ce23e455c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_runs', sa.Column('step_timings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_runs', 'step_timings')
    # ### end Alembic commands ###
