"""add processing run review fields

Revision ID: d58dc395f17f
Revises: c7f1a2b3d4e5
Create Date: 2026-09-27 14:26:58.274616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd58dc395f17f'
down_revision: Union[str, Sequence[str], None] = 'c7f1a2b3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_runs', sa.Column('review_status', sa.String(length=20), nullable=True))
    op.add_column('processing_runs', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processing_runs', sa.Column('reviewed_by_type', sa.String(length=20), nullable=True))
    op.add_column('processing_runs', sa.Column('reviewed_by_subject', sa.String(length=255), nullable=True))
    op.add_column('processing_runs', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column('processing_runs', sa.Column('corrected_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_processing_runs_review_status'), 'processing_runs', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_runs_review_status'), table_name='processing_runs')
    op.drop_column('processing_runs', 'corrected_values')
    op.drop_column('processing_runs', 'review_comment')
    op.drop_column('processing_runs', 'reviewed_by_subject')
    op.drop_column('processing_runs', 'reviewed_by_type')
    op.drop_column('processing_runs', 'reviewed_at')
    op.drop_column('processing_runs', 'review_status')
    # ### end Alembic commands ###
